services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - fiware
    restart: unless-stopped

  crate:
    image: crate/crate:latest
    container_name: crate
    ports:
      - "4200:4200"
      - "5432:5432" # Porta PostgreSQL para CrateDB (se você usar)
    command: ["crate", "-Cdiscovery.type=single-node", "-Ccluster.name=docker-cluster", "-Cgateway.expected_nodes=1", "-Cgateway.recover_after_nodes=1"] # Comando mais robusto para single-node
    environment:
      - CRATE_HEAP_SIZE=1g
    volumes:
      - crate_data:/data
    networks:
      - fiware
    restart: unless-stopped

  quantumleap:
    image: orchestracities/quantumleap:latest
    container_name: quantumleap
    depends_on:
      - crate
      - orion
    ports:
      - "8668:8668"
    environment:
      - CRATE_HOST=crate
      - QL_CRATE_HOST=crate
      - CRATE_PORT=4200
      - QL_DB_NAME=doc
      - USE_GEOCODING=False
      - LOGLEVEL=INFO
    networks:
      - fiware
    restart: unless-stopped

  orion:
    image: telefonicaiot/fiware-orion:latest
    container_name: orion
    depends_on:
      - mongo
    ports:
      - "1026:1026"
    command: -dbURI mongodb://mongo
    networks:
      - fiware
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - fiware
    restart: unless-stopped

  init-subscriptions:
    image: curlimages/curl:latest
    container_name: init-subscriptions
    depends_on:
      - orion
      - quantumleap
    entrypoint: [ "sh", "-c", "sleep 10 && sh /create_subscriptions.sh" ]
    volumes:
      - ./create_subscriptions.sh:/create_subscriptions.sh
    networks:
      - fiware
    restart: "no"

  weather-app:
    build:
      context: .
    depends_on:
      - orion
      - quantumleap
      - crate
      - init-subscriptions
    environment:
      - PORT=8080
      - SPRING_PROFILES_ACTIVE=production
      - WEATHER_API_URL=https://api.open-meteo.com/v1
      - ORION_API_URL=http://orion:1026
    ports:
      - "8080:8080"
    networks:
      - fiware
    restart: unless-stopped

networks:
  fiware:
    driver: bridge

volumes:
  crate_data:
  mongo_data: